# Generated by Django 5.0.12 on 2025-02-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakeries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakery",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
